# Generated by Django 3.0.6 on 2020-05-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('land', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.CharField(default='$9.95', max_length=64),
        ),
    ]
